apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: {{ .Values.service.name }}
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443        
  selector:
    app: {{ .Chart.Name }}
