apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab-dev
type: Opaque
stringData:
  runner-registration-token: glrt-SukAnVavfyWJD8_PnD1Y
---
apiVersion: apps.gitlab.com/v1beta2 
kind: Runner
metadata:
 name: gitlab-runner
 namespace: gitlab-dev
spec:
 gitlabUrl: https://gitlab.com/
 buildImage: alpine 
 token: gitlab-runner-secret
 tags: uni-runner
 config: custom-config-toml
 ca: gitlab